name: login_module
description: login module.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.2.0
  google_sign_in: ^5.2.1
  the_apple_sign_in: ^1.1.1
  webview_flutter: ^2.8.0
  flutter_facebook_auth: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/images/apple-logo.png
    - assets/images/google-logo.png
    - assets/images/facebook-logo.png
    - assets/images/2.0x/google-logo.png
    - assets/images/2.0x/facebook-logo.png
    - assets/images/3.0x/google-logo.png
    - assets/images/3.0x/facebook-logo.png
